name: Deploy doxa-board App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Stop and Remove Existing Containers
        run: |
          docker stop doxa-board || true
          docker rm doxa-board || true

      - name: Build Docker Image
        run: docker build -t doxa-board .

      - name: Run New Docker Container
        run: docker run -d -p 3000:3000 doxa-board
